sudo: required

language: python

python:
  - 2.7

services:
    - postgresql

#install dependencies
install: pip install -qr vagrant/tradyfit/requirements.txt

#create database
before_script:
  - sudo su postgres -c 'createuser -dRS vagrant'
  - sudo su vagrant -c 'createdb tradyfit_test'

#run tests
script: python vagrant/tradyfit/manage.py test

