language: python

python:
  - 2.7.9

services:
    - postgresql

#install dependencies
install:
  - pip install -qr requirements.txt
  - pip install coveralls

#create database
before_script:
  - cd vagrant/tradyfit
  - psql -c 'create database tradyfit_test;' -U postgres
  #enable PostGIS
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d tradyfit_test
  #enable Topology
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d tradyfit_test

#run tests
script:
  coverage run --source=app manage.py test

after_success:
  coveralls

