site_name: TradyFit
pages:
- [index.md, Home]
- [architecture.md, Architecture design]
- [api.md, REST API]
- [database.md, Database]
- [testing.md, Testing Strategy]
- [notes.md, Notes]
- [about.md, About]
theme: readthedocs
