"""added user_id foreign key to items table

Revision ID: 1ac6930075e7
Revises: 46a8aad56
Create Date: 2015-03-01 07:10:16.474428

"""

# revision identifiers, used by Alembic.
revision = '1ac6930075e7'
down_revision = '46a8aad56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    ### end Alembic commands ###
