"""added modified field to item db

Revision ID: 1c047a351906
Revises: 480a467cb5dc
Create Date: 2015-02-26 19:18:18.525913

"""

# revision identifiers, used by Alembic.
revision = '1c047a351906'
down_revision = '480a467cb5dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('modified', sa.DateTime(), nullable=True))
    op.create_index(u'ix_items_modified', 'items', ['modified'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_items_modified', table_name='items')
    op.drop_column('items', 'modified')
    ### end Alembic commands ###
