"""added latitude and longitude to Users table

Revision ID: 1e68ebff1102
Revises: 52ef8c78af19
Create Date: 2015-04-12 00:34:32.451174

"""

# revision identifiers, used by Alembic.
revision = '1e68ebff1102'
down_revision = '52ef8c78af19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    ### end Alembic commands ###
