"""added country,state,city to items

Revision ID: 2496c486b030
Revises: 49b6d8f6d4c8
Create Date: 2015-04-19 16:26:23.742736

"""

# revision identifiers, used by Alembic.
revision = '2496c486b030'
down_revision = '49b6d8f6d4c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('items', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('items', sa.Column('state', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'state')
    op.drop_column('items', 'country')
    op.drop_column('items', 'city')
    ### end Alembic commands ###
