"""added search_vector to items table

Revision ID: 35b2b9f7b64e
Revises: 1c047a351906
Create Date: 2015-02-28 17:00:36.979960

"""

# revision identifiers, used by Alembic.
revision = '35b2b9f7b64e'
down_revision = '1c047a351906'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
from sqlalchemy_utils.types import TSVectorType

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.add_column('items', sa.Column('search_vector', TSVectorType(), nullable=True))
    op.create_index('ix_items_search_vector', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    sync_trigger(conn, 'items', 'search_vector', ['name', 'description'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.drop_index('ix_items_search_vector', table_name='items')
    op.drop_column('items', 'search_vector')
    sync_trigger(conn, 'items', 'search_vector', ['name', 'description'])
    ### end Alembic commands ###
