"""added user avatar_url

Revision ID: 3fc0c20475df
Revises: 1ac6930075e7
Create Date: 2015-04-08 18:33:13.155331

"""

# revision identifiers, used by Alembic.
revision = '3fc0c20475df'
down_revision = '1ac6930075e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(u'users_avatar_url_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_avatar_url_key', 'users', ['avatar_url'])
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
