"""added geoalchemy point to search items nearby

Revision ID: 49b6d8f6d4c8
Revises: e0673de42c3
Create Date: 2015-04-17 21:19:36.464638

"""

# revision identifiers, used by Alembic.
revision = '49b6d8f6d4c8'
down_revision = 'e0673de42c3'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('items', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True))
    op.drop_column('items', 'latitude')
    op.drop_column('items', 'longitude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True))
    op.drop_column('items', 'location')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    ### end Alembic commands ###
