"""added item image_url

Revision ID: 52ef8c78af19
Revises: 3fc0c20475df
Create Date: 2015-04-08 18:33:51.596104

"""

# revision identifiers, used by Alembic.
revision = '52ef8c78af19'
down_revision = '3fc0c20475df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image_url')
    ### end Alembic commands ###
