"""deleted has_notifications flag from users table

Revision ID: 7d03c5d0603
Revises: 4815c5261520
Create Date: 2015-04-15 19:48:22.460189

"""

# revision identifiers, used by Alembic.
revision = '7d03c5d0603'
down_revision = '4815c5261520'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_notifications')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
